#!/usr/bin/env python3
"""
Render an anti-aliased console font for RV-9.

The panel is 16-bit colour, so glyphs are stored as 4-bit coverage (16
levels) rather than 1-bit on/off. The driver blends foreground to
background through that coverage, which is what removes the staircase
edges from a doubled bitmap font.

Cell is 10x20: tall enough to read on a 1.47" panel, narrow enough for 30
columns across the long axis.
"""
import subprocess
import sys
from PIL import Image, ImageDraw, ImageFont

FIRST, LAST = 32, 126
CELL_W, CELL_H = 10, 20

path = subprocess.run(["fc-match", "-f", "%{file}", "DejaVu Sans Mono"],
                      capture_output=True, text=True).stdout.strip()
if not path:
    sys.exit("no monospace font found")

# Largest size whose advance and line height both fit the cell.
best = None
for size in range(8, 26):
    f = ImageFont.truetype(path, size)
    ascent, descent = f.getmetrics()
    advance = f.getlength("M")
    if advance <= CELL_W and (ascent + descent) <= CELL_H:
        best = (size, f, ascent)
    else:
        break
if best is None:
    sys.exit(f"nothing fits {CELL_W}x{CELL_H}")

size, font, ascent = best
baseline = ascent + (CELL_H - ascent - font.getmetrics()[1]) // 2

glyphs = []
for c in range(FIRST, LAST + 1):
    img = Image.new("L", (CELL_W, CELL_H), 0)
    ImageDraw.Draw(img).text((0, baseline), chr(c), font=font, fill=255,
                             anchor="ls")
    rows = []
    for y in range(CELL_H):
        packed = bytearray()
        for x in range(0, CELL_W, 2):
            hi = img.getpixel((x, y)) >> 4
            lo = img.getpixel((x + 1, y)) >> 4 if x + 1 < CELL_W else 0
            packed.append((hi << 4) | lo)
        rows.append(bytes(packed))
    glyphs.append(rows)

stride = (CELL_W + 1) // 2
with open("components/rv9_io/src/font.c", "w") as f:
    f.write(f'''/*
 * Anti-aliased console font, ASCII {FIRST}..{LAST}, {CELL_W}x{CELL_H} cells.
 *
 * Generated by tools/mkfont.py from {path.split("/")[-1]} at {size}px.
 * Do not edit by hand -- rerun the generator.
 *
 * Two pixels per byte, 4 bits of coverage each, high nibble leftmost.
 * The driver blends foreground to background through that coverage.
 */
#include <stdint.h>

const unsigned char rv9_font[{LAST - FIRST + 1}][{CELL_H}][{stride}] = {{
''')
    for c, rows in zip(range(FIRST, LAST + 1), glyphs):
        ch = chr(c)
        label = {"\\\\": "backslash", "'": "apostrophe"}.get(ch, f"'{ch}'")
        f.write(f"    {{  /* {label} */\n")
        for r in rows:
            f.write("        { " + ", ".join(f"0x{b:02x}" for b in r) + " },\n")
        f.write("    },\n")
    f.write("};\n")

print(f"font: {path.split('/')[-1]} at {size}px, {CELL_W}x{CELL_H} cells, "
      f"{LAST-FIRST+1} glyphs, {(LAST-FIRST+1)*CELL_H*stride} bytes")

shades = " .:-=+*#%@"
for probe in "RV9a":
    print(f"\n  '{probe}'")
    for row in glyphs[ord(probe) - FIRST]:
        line = ""
        for b in row:
            for nib in ((b >> 4) & 0xF, b & 0xF):
                line += shades[nib * (len(shades) - 1) // 15]
        print("   " + line)
