#!/usr/bin/env python3
"""Render an 8x8 bitmap font for the RV-9 LCD console."""
import subprocess, sys
from PIL import Image, ImageDraw, ImageFont

FIRST, LAST = 32, 126
W = H = 8

path = subprocess.run(["fc-match", "-f", "%{file}", "DejaVu Sans Mono"],
                      capture_output=True, text=True).stdout.strip()
if not path:
    sys.exit("no monospace font found")

# Find the largest size whose glyphs still fit the 8x8 cell.
best = None
for size in range(6, 15):
    f = ImageFont.truetype(path, size)
    ok, maxw, maxh = True, 0, 0
    for c in range(FIRST, LAST + 1):
        box = f.getbbox(chr(c))
        if not box:
            continue
        maxw = max(maxw, box[2])
        maxh = max(maxh, box[3] - box[1])
    if maxw <= W and maxh <= H:
        best = (size, f)
    else:
        break
if best is None:
    sys.exit("could not fit any size into 8x8")

size, font = best
ascent, _ = font.getmetrics()

glyphs = []
for c in range(FIRST, LAST + 1):
    img = Image.new("1", (W, H), 0)
    d = ImageDraw.Draw(img)
    # Baseline placement: push the glyph down so descenders have room.
    d.text((0, H - ascent - 1), chr(c), font=font, fill=1)
    rows = []
    for y in range(H):
        bits = 0
        for x in range(W):
            if img.getpixel((x, y)):
                bits |= 1 << (7 - x)     # MSB is leftmost pixel
        rows.append(bits)
    glyphs.append(rows)

with open("components/rv9_io/src/font8x8.c", "w") as f:
    f.write(f'''/*
 * 8x8 console font, ASCII {FIRST}..{LAST}.
 *
 * Generated by tools/mkfont.py from {path.split("/")[-1]} at {size}px.
 * Do not edit by hand -- rerun the generator.
 *
 * One byte per row, MSB is the leftmost pixel.
 */
#include <stdint.h>

const unsigned char rv9_font8x8[{LAST - FIRST + 1}][8] = {{
''')
    for c, rows in zip(range(FIRST, LAST + 1), glyphs):
        ch = chr(c).replace("\\\\", "\\\\\\\\").replace("'", "\\\\'")
        body = ", ".join(f"0x{r:02x}" for r in rows)
        f.write(f"    {{ {body} }},   /* '{ch}' */\n")
    f.write("};\n")

print(f"font: {path.split('/')[-1]} at {size}px, {LAST-FIRST+1} glyphs")
for probe in "ARV9g#":
    print(f"\n  '{probe}'")
    for row in glyphs[ord(probe) - FIRST]:
        print("   " + "".join("#" if row & (1 << (7 - x)) else "." for x in range(8)))
